import { useEffect, useState, type KeyboardEvent, type MouseEvent } from "react";
import { Link, useLocation, useParams } from "wouter";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRight, BookOpen, History, MessageCircle, Package, Printer, ShieldCheck, Truck, UserRound, WalletCards } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/contexts/AuthContext";
import { getGetSiteSettingsQueryKey, useGetSiteSettings } from "@workspace/api-client-react";

const statusLabels: Record<string, string> = { new: "جديد", awaiting_confirmation: "بانتظار التأكيد", confirmed: "مؤكد", preparing: "جاري التجهيز", ready_for_shipping: "جاهز للشحن", shipped: "تم الشحن", out_for_delivery: "خرج للتوصيل", delivered: "تم التسليم", delivery_failed: "تعذر التسليم", returned: "مرتجع", partially_returned: "مرتجع جزئيًا", cancelled: "ملغي" };
type OrderListItem = { id: number; orderNumber: string; customerName: string; mobile: string; governorate: string; total: number; status: string; paymentStatus?: string; paymentMethod?: string; paymentPlan?: string | null; transferMethod?: string | null; paidAmount?: number; remainingAmount?: number | null; createdAt: string };
type OrderListResponse = { items: OrderListItem[]; total: number; page: number; limit: number };
type DetailedOrder = OrderListItem & {
  primaryPhone?: string; primaryPhoneHasWhatsApp: boolean; altMobile?: string | null; alternatePhone?: string | null; alternatePhoneHasWhatsApp: boolean; preferredWhatsAppPhone?: string | null; city: string; detailedAddress: string; landmark?: string | null; deliveryNotes?: string | null; orderNotes?: string | null; internalNotes?: string | null;
  subtotal: number; discount: number; couponDiscount: number; couponCode?: string | null; shippingCost: number; shippingBaseCost: number; shippingSurcharge: number; shippingDiscount: number; freeShippingReason?: string | null;
  shippingRuleSnapshot?: Record<string, unknown> | null; paymentMethod: string; paymentStatus: string; paymentPlan?: string | null; transferMethod?: string | null; requiredPaymentAmount?: number | null; paidAmount: number; remainingAmount?: number | null; assignedTo?: string | null; trackingNumber?: string | null; shippingCompany?: string | null;
  items: { productId?: number | null; nameAr: string; coverImage?: string | null; quantity: number; unitPrice: number; discount: number; subtotal: number }[];
  statusHistory: { status: string; notes?: string | null; employeeName?: string | null; createdAt: string }[];
  inventoryMovements: { id: number; productNameAr?: string | null; movementType: string; quantityBefore: number; quantityAfter: number; quantityChanged: number; reason?: string | null; employeeName?: string | null; createdAt: string }[];
  auditHistory: { id: number; action: string; description: string; employeeName?: string | null; createdAt: string }[];
};

class ApiError extends Error { constructor(message: string, readonly status: number) { super(message); } }
async function request<T>(url: string, init?: RequestInit): Promise<T> {
  const response = await fetch(url, { credentials: "include", ...init, headers: { ...(init?.body ? { "content-type": "application/json" } : {}), ...init?.headers } });
  const body = await response.json().catch(() => null);
  if (!response.ok) throw new ApiError(body?.error || "تعذر الاتصال بالخادم", response.status);
  return body as T;
}
function interactive(target: EventTarget | null) { return target instanceof HTMLElement && Boolean(target.closest("a,button,input,select,textarea,[role=button]")); }

export function AdminOrders() {
  const [, navigate] = useLocation();
  const initial = new URLSearchParams(window.location.search);
  const [page, setPage] = useState(() => Math.max(1, Number(initial.get("page")) || 1));
  const [status, setStatus] = useState(() => initial.get("status") || "all");
  const [query, setQuery] = useState(() => initial.get("q") || "");
  useEffect(() => {
    const params = new URLSearchParams(); if (page > 1) params.set("page", String(page)); if (status !== "all") params.set("status", status); if (query) params.set("q", query);
    window.history.replaceState(null, "", `${window.location.pathname}${params.size ? `?${params}` : ""}`);
  }, [page, query, status]);
  const listUrl = `/api/admin/orders?page=${page}&limit=20${query ? `&q=${encodeURIComponent(query)}` : ""}${status !== "all" ? `&status=${status}` : ""}`;
  const orders = useQuery({ queryKey: ["admin-orders", page, query, status], queryFn: () => request<OrderListResponse>(listUrl) });
  const returnTo = `${window.location.pathname}${window.location.search}`;
  const detailUrl = (id: number) => `/admin/orders/${id}?returnTo=${encodeURIComponent(returnTo)}`;
  const openRow = (event: MouseEvent<HTMLTableRowElement>, id: number) => { if (interactive(event.target)) return; if (event.metaKey || event.ctrlKey) window.open(detailUrl(id), "_blank", "noopener"); else navigate(detailUrl(id)); };
  const openKeyboard = (event: KeyboardEvent<HTMLTableRowElement>, id: number) => { if (event.key === "Enter" && !interactive(event.target)) { event.preventDefault(); navigate(detailUrl(id)); } };
  return <section className="space-y-6" dir="rtl">
    <div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-bold">إدارة الطلبات</h1><p className="text-sm text-muted-foreground">اضغط على أي صف لفتح كل تفاصيل الطلب</p></div><div className="flex flex-1 flex-wrap justify-end gap-2"><Input className="min-w-56 max-w-80" placeholder="رقم الطلب أو العميل أو الهاتف" value={query} onChange={event => { setQuery(event.target.value); setPage(1); }} /><Select value={status} onValueChange={value => { setStatus(value); setPage(1); }}><SelectTrigger className="w-52"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">كل الحالات</SelectItem>{Object.entries(statusLabels).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div></div>
    <Card className="overflow-hidden"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>رقم الطلب</TableHead><TableHead>العميل</TableHead><TableHead>المحافظة</TableHead><TableHead>الإجمالي</TableHead><TableHead>حالة الطلب</TableHead><TableHead>حالة الدفع</TableHead><TableHead>التاريخ</TableHead></TableRow></TableHeader><TableBody>
      {orders.isLoading && <TableRow><TableCell colSpan={7} className="py-14 text-center">جاري تحميل الطلبات...</TableCell></TableRow>}
      {orders.isError && <TableRow><TableCell colSpan={7} className="py-14 text-center text-destructive">تعذر تحميل الطلبات. حاول تحديث الصفحة.</TableCell></TableRow>}
      {orders.data?.items.map(order => <TableRow key={order.id} tabIndex={0} role="link" aria-label={`فتح الطلب ${order.orderNumber}`} onClick={event => openRow(event, order.id)} onKeyDown={event => openKeyboard(event, order.id)} onAuxClick={event => { if (event.button === 1 && !interactive(event.target)) window.open(detailUrl(order.id), "_blank", "noopener"); }} className="cursor-pointer transition-colors hover:bg-primary/5 focus-visible:bg-primary/5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-primary"><TableCell><Link className="font-mono font-bold text-primary underline-offset-4 hover:underline" href={detailUrl(order.id)}>{order.orderNumber}</Link></TableCell><TableCell><strong>{order.customerName}</strong><div className="text-xs text-muted-foreground" dir="ltr">{order.mobile}</div></TableCell><TableCell>{order.governorate}</TableCell><TableCell className="font-bold">{order.total.toFixed(2)} ج.م</TableCell><TableCell><Badge variant="outline">{statusLabels[order.status] || order.status}</Badge></TableCell><TableCell><Badge variant="secondary">{paymentLabel(order.paymentStatus)}</Badge></TableCell><TableCell>{new Date(order.createdAt).toLocaleDateString("ar-EG")}</TableCell></TableRow>)}
      {!orders.isLoading && !orders.isError && !orders.data?.items.length && <TableRow><TableCell colSpan={7} className="py-14 text-center">لا توجد طلبات مطابقة للبحث</TableCell></TableRow>}
    </TableBody></Table></div></Card>
    {orders.data && orders.data.total > orders.data.limit && <div className="flex items-center justify-between"><Button variant="outline" disabled={page === 1} onClick={() => setPage(value => value - 1)}>السابق</Button><span className="text-sm">صفحة {page} من {Math.ceil(orders.data.total / orders.data.limit)}</span><Button variant="outline" disabled={page * orders.data.limit >= orders.data.total} onClick={() => setPage(value => value + 1)}>التالي</Button></div>}
  </section>;
}

export function AdminOrderDetail() {
  const { id } = useParams<{ id: string }>(); const orderId = Number(id); const [, navigate] = useLocation(); const queryClient = useQueryClient(); const { toast } = useToast(); const { admin } = useAuth();
  const params = new URLSearchParams(window.location.search); const requestedReturn = params.get("returnTo"); const returnTo = requestedReturn?.startsWith("/admin/orders") ? requestedReturn : "/admin/orders";
  const canEdit = admin?.role === "owner" || admin?.role === "administrator" || admin?.permissions?.includes("orders.edit");
  const canWhatsApp = admin?.role === "owner" || admin?.role === "administrator" || admin?.permissions?.includes("orders.whatsapp");
  const { data: settings } = useGetSiteSettings({ query: { queryKey: getGetSiteSettingsQueryKey(), staleTime: 60_000 } });
  const orderQuery = useQuery({ queryKey: ["admin-order", orderId], enabled: Number.isInteger(orderId) && orderId > 0, retry: false, queryFn: () => request<DetailedOrder>(`/api/admin/orders/${orderId}`) });
  const [status, setStatus] = useState("");
  const updateStatus = useMutation({ mutationFn: (next: string) => request(`/api/admin/orders/${orderId}/status`, { method: "PATCH", body: JSON.stringify({ status: next }) }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["admin-order", orderId] }); toast({ title: "تم تحديث حالة الطلب", variant: "success" }); }, onError: (error: Error) => toast({ title: "تعذر تحديث حالة الطلب", description: error.message, variant: "destructive" }) });
  const cancellation = useMutation({ mutationFn: (decision: "approved" | "rejected") => request(`/api/admin/orders/${orderId}/cancellation`, { method: "PATCH", body: JSON.stringify({ decision }) }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["admin-order", orderId] }); toast({ title: "تم تسجيل قرار طلب الإلغاء", variant: "success" }); }, onError: (error: Error) => toast({ title: "تعذر تنفيذ القرار", description: error.message, variant: "destructive" }) });
  const openWhatsApp = async () => {
    const popup = window.open("about:blank", "maktaba-order-whatsapp");
    if (popup) { popup.document.title = "جاري فتح واتساب..."; popup.opener = null; }
    try { const data = await request<{ url: string }>(`/api/admin/orders/${orderId}/whatsapp`, { method: "POST" }); if (popup) popup.location.href = data.url; else window.open(data.url, "_blank", "noopener,noreferrer"); }
    catch (error) { popup?.close(); toast({ title: "تعذر فتح واتساب", description: error instanceof Error ? error.message : String(error), variant: "destructive" }); }
  };
  if (orderQuery.isLoading) return <div className="py-20 text-center">جاري تحميل الطلب...</div>;
  if (orderQuery.isError || !orderQuery.data) { const notFound = orderQuery.error instanceof ApiError && orderQuery.error.status === 404; return <Card className="mx-auto mt-16 max-w-xl text-center"><CardContent className="py-14"><BookOpen className="mx-auto mb-4 h-14 w-14 text-muted-foreground/30"/><h1 className="text-2xl font-black">{notFound ? "الطلب غير موجود" : "تعذر تحميل الطلب"}</h1><p className="mt-2 text-muted-foreground">{notFound ? "ربما تم حذف الطلب أو أن الرابط لم يعد صالحًا." : orderQuery.error?.message || "حدث خطأ غير متوقع"}</p><div className="mt-6 flex justify-center gap-2"><Button onClick={() => navigate(returnTo)}>العودة للطلبات</Button><Button variant="outline" onClick={() => orderQuery.refetch()}>إعادة المحاولة</Button></div></CardContent></Card>; }
  const order = orderQuery.data; const snapshot = order.shippingRuleSnapshot || {};
  const hasWhatsApp = Boolean(order.preferredWhatsAppPhone || order.primaryPhoneHasWhatsApp || (order.altMobile && order.alternatePhoneHasWhatsApp));
  const invoiceLogo = settings?.mainLogoUrl || settings?.lightBackgroundLogoUrl || settings?.logoUrl;
  return <section className="space-y-6" dir="rtl">
    <div className="hidden items-center justify-between border-b pb-5 print:flex">{invoiceLogo ? <img src={invoiceLogo} alt={settings?.storeNameAr || "مكتبة دوت كوم"} className="max-h-16 max-w-52 object-contain" /> : <strong className="text-2xl">{settings?.storeNameAr || "مكتبة دوت كوم"}</strong>}<div className="text-left"><strong>فاتورة غير ضريبية</strong><p>{order.orderNumber}</p></div></div>
    <div className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border bg-card p-5 shadow-sm"><div><Button variant="ghost" className="mb-2 px-0 print:hidden" onClick={() => navigate(returnTo)}><ArrowRight className="ml-2 h-4 w-4"/>العودة إلى نفس نتائج البحث</Button><div className="flex flex-wrap items-center gap-3"><h1 className="text-2xl font-black sm:text-3xl">الطلب {order.orderNumber}</h1><Badge className="text-sm">{statusLabels[order.status] || order.status}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{new Date(order.createdAt).toLocaleString("ar-EG")}</p></div><div className="flex flex-wrap gap-2 print:hidden"><Button variant="outline" onClick={() => window.print()}><Printer className="ml-2 h-4 w-4"/>طباعة الفاتورة</Button>{canWhatsApp && <Button variant="outline" disabled={!hasWhatsApp} title={!hasWhatsApp ? "لا يوجد رقم محدد عليه واتساب" : "فتح رسالة الطلب الجاهزة"} onClick={() => void openWhatsApp()}><MessageCircle className="ml-2 h-4 w-4"/>فتح واتساب</Button>}</div></div>
    <div className="grid gap-6 xl:grid-cols-3"><Card className="xl:col-span-2"><CardHeader><CardTitle className="flex gap-2"><Package className="h-5 w-5"/>المنتجات</CardTitle></CardHeader><CardContent className="space-y-4">{order.items.map((item, index) => <div key={`${item.productId}-${index}`} className="grid grid-cols-[64px_1fr_auto] items-center gap-4 border-b pb-4"><div className="h-20 w-16 overflow-hidden rounded-lg bg-muted">{item.coverImage ? <img src={item.coverImage} alt={item.nameAr} className="h-full w-full object-cover"/> : <BookOpen className="h-full w-full p-4 text-muted-foreground/30"/>}</div><div><strong>{item.nameAr}</strong><p className="text-sm text-muted-foreground">{item.quantity} × {item.unitPrice.toFixed(2)} ج.م {item.discount > 0 ? `— خصم ${item.discount.toFixed(2)} ج.م` : ""}</p></div><strong>{item.subtotal.toFixed(2)} ج.م</strong></div>)}</CardContent></Card>
      <Card><CardHeader><CardTitle className="flex gap-2"><UserRound className="h-5 w-5"/>العميل والعنوان</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-lg font-bold">{order.customerName}</p><PhoneRow label="الرقم الأساسي" phone={order.mobile} hasWhatsApp={order.primaryPhoneHasWhatsApp} preferred={order.preferredWhatsAppPhone === order.mobile} />{order.altMobile && <PhoneRow label="الرقم البديل" phone={order.altMobile} hasWhatsApp={order.alternatePhoneHasWhatsApp} preferred={order.preferredWhatsAppPhone === order.altMobile} />}<div className="rounded-xl bg-slate-50 p-3"><p className="font-bold">{order.governorate} — {order.city}</p><p className="mt-1 text-sm">{order.detailedAddress}</p>{order.landmark && <p className="mt-1 text-xs text-muted-foreground">علامة مميزة: {order.landmark}</p>}</div>{order.deliveryNotes && <p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">ملاحظات التوصيل: {order.deliveryNotes}</p>}<hr/><p>الموظف المسؤول: <strong>{order.assignedTo || "غير مسند"}</strong></p><div className="rounded-xl border border-sky-200 bg-sky-50 p-3"><p className="flex items-center gap-2 font-bold"><WalletCards className="h-4 w-4" />{order.paymentMethod === "cash_on_delivery" ? "دفع عند الاستلام — طلب سابق" : order.paymentPlan === "full" ? "تحويل كامل مقدمًا" : "100 جنيه مقدم والباقي عند الاستلام"}</p><p className="mt-1 text-sm">الحالة: {paymentLabel(order.paymentStatus)}</p>{order.paymentMethod === "manual_transfer" && <Button className="mt-3" size="sm" variant="outline" asChild><Link href="/admin/payments">فتح مراجعة المدفوعات</Link></Button>}</div></CardContent></Card>
    </div>
    <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex gap-2"><Truck className="h-5 w-5"/>حساب الشحن المحفوظ</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><Line label="أساس الشحن" value={`${order.shippingBaseCost.toFixed(2)} ج.م`}/><Line label="إضافة المدينة/المنطقة" value={`${order.shippingSurcharge.toFixed(2)} ج.م`}/><Line label="خصم الشحن" value={`${order.shippingDiscount.toFixed(2)} ج.م`}/><Line label="الشحن النهائي" value={`${order.shippingCost.toFixed(2)} ج.م`}/>{order.freeShippingReason && <p className="rounded-lg bg-emerald-50 p-3 font-bold text-emerald-700">{order.freeShippingReason}</p>}<p className="pt-2 text-muted-foreground">نسخة القاعدة: {String(snapshot.minDeliveryDays ?? "—")} إلى {String(snapshot.maxDeliveryDays ?? "—")} أيام عمل • {String(snapshot.rule ?? "قاعدة الشحن المحفوظة")}</p></CardContent></Card>
      <Card><CardHeader><CardTitle>الإجماليات</CardTitle></CardHeader><CardContent className="space-y-3"><Line label="قيمة المنتجات" value={`${order.subtotal.toFixed(2)} ج.م`}/><Line label="خصم المنتجات" value={`-${order.discount.toFixed(2)} ج.م`}/><Line label={`خصم الكوبون ${order.couponCode || ""}`} value={`-${order.couponDiscount.toFixed(2)} ج.م`}/><Line label="الشحن" value={`${order.shippingCost.toFixed(2)} ج.م`}/><div className="flex justify-between border-t pt-4 text-xl font-black"><span>الإجمالي النهائي</span><span>{order.total.toFixed(2)} ج.م</span></div>{order.paymentMethod === "manual_transfer" && <><Line label="المدفوع المعتمد" value={`${order.paidAmount.toFixed(2)} ج.م`}/><Line label="المتبقي" value={`${Number(order.remainingAmount ?? order.total).toFixed(2)} ج.م`}/></>}</CardContent></Card>
    </div>
    {canEdit && <Card className="print:hidden"><CardHeader><CardTitle>تحديث حالة الطلب</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-3"><Select value={status || order.status} onValueChange={setStatus}><SelectTrigger className="w-64"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(statusLabels).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select><Button disabled={updateStatus.isPending || (!status || status === order.status)} onClick={() => updateStatus.mutate(status)}>حفظ الحالة</Button><div className="me-auto flex flex-wrap gap-2"><Button variant="outline" disabled={cancellation.isPending} onClick={() => cancellation.mutate("rejected")}>رفض طلب الإلغاء</Button><Button variant="destructive" disabled={cancellation.isPending} onClick={() => cancellation.mutate("approved")}>الموافقة على الإلغاء</Button></div></CardContent></Card>}
    <div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle className="flex gap-2"><History className="h-5 w-5"/>سجل الحالة</CardTitle></CardHeader><CardContent className="space-y-4">{order.statusHistory.length ? order.statusHistory.map((entry, index) => <div key={index} className="border-r-2 border-primary pr-4"><strong>{statusLabels[entry.status] || entry.status}</strong><p className="text-sm text-muted-foreground">{entry.notes || "تحديث الحالة"} • {entry.employeeName || "النظام"} • {new Date(entry.createdAt).toLocaleString("ar-EG")}</p></div>) : <p className="text-muted-foreground">لا يوجد سجل بعد</p>}</CardContent></Card>
      <Card><CardHeader><CardTitle>حركات المخزون</CardTitle></CardHeader><CardContent className="space-y-3">{order.inventoryMovements.length ? order.inventoryMovements.map(movement => <div key={movement.id} className="flex justify-between rounded-xl border p-3"><div><strong>{movement.productNameAr || `منتج #${movement.id}`}</strong><p className="text-xs text-muted-foreground">{movement.reason || movement.movementType} • {new Date(movement.createdAt).toLocaleString("ar-EG")}</p></div><Badge variant="outline">{movement.quantityBefore} ← {movement.quantityAfter} ({movement.quantityChanged > 0 ? "+" : ""}{movement.quantityChanged})</Badge></div>) : <p className="text-muted-foreground">لا توجد حركات مرتبطة</p>}</CardContent></Card>
    </div>
    <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>الملاحظات</CardTitle></CardHeader><CardContent className="space-y-3"><p><strong>ملاحظات العميل:</strong> {order.orderNotes || "لا توجد"}</p><p><strong>ملاحظات داخلية:</strong> {order.internalNotes || "لا توجد"}</p></CardContent></Card><Card><CardHeader><CardTitle className="flex gap-2"><ShieldCheck className="h-5 w-5"/>سجل التدقيق</CardTitle></CardHeader><CardContent className="space-y-3">{order.auditHistory.length ? order.auditHistory.map(entry => <div key={entry.id} className="border-b pb-3"><strong>{entry.description}</strong><p className="text-xs text-muted-foreground">{entry.employeeName || "النظام"} • {new Date(entry.createdAt).toLocaleString("ar-EG")}</p></div>) : <p className="text-muted-foreground">لا توجد إجراءات إدارية مسجلة</p>}</CardContent></Card></div>
  </section>;
}
function Line({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4"><span>{label}</span><strong>{value}</strong></div>; }
function PhoneRow({ label, phone, hasWhatsApp, preferred }: { label: string; phone: string; hasWhatsApp: boolean; preferred: boolean }) { return <div className="rounded-xl border p-3"><div className="mb-2 flex flex-wrap items-center gap-2 text-xs"><span className="text-muted-foreground">{label}</span>{hasWhatsApp && <Badge variant="outline" className="border-emerald-200 text-emerald-700">واتساب</Badge>}{preferred && <Badge className="bg-emerald-600">المفضل</Badge>}</div><a href={`tel:${phone}`} dir="ltr" className="block text-right text-lg font-black text-primary underline-offset-4 hover:underline">{phone}</a></div>; }
function paymentLabel(status?: string) { return ({ awaiting_transfer: "بانتظار التحويل", pending_verification: "في انتظار المراجعة", partially_paid: "مدفوع جزئيًا", fully_paid: "مدفوع بالكامل", rejected: "مرفوض", needs_review: "يحتاج مراجعة", cash_on_delivery: "عند الاستلام" } as Record<string, string>)[status || ""] || status || "—"; }
