import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Clock3, Eye, ImageIcon, RefreshCw, Search, Settings2, ShieldAlert, WalletCards, XCircle } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { AdminPageState } from "@/components/admin/AdminPageState";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/hooks/use-toast";
import { adminApi, useAdminResource } from "@/lib/admin-api";

type Payment = {
  id: number; orderId: number; orderNumber: string; customerName: string; customerPhone: string; orderTotal: number;
  paymentPlan: "deposit_100" | "full"; amount: number; paidAmount: number; remainingAmount: number;
  transferMethod: "instapay" | "mobile_wallet"; senderIdentifier: string; transactionReference: string | null;
  proofImageUrl: string | null; status: "pending_verification" | "confirmed" | "rejected" | "needs_review";
  riskLevel: "none" | "yellow" | "orange" | "red"; riskReasons: string[]; previousUseCount: number;
  lastSenderUseAt: string; reviewerName: string | null; rejectionReason: string | null; reviewNotes: string | null;
  reviewedAt: string | null; createdAt: string;
};
type PaymentDetail = Payment & {
  reviewHistory: { id: number; fromStatus: string | null; toStatus: string; employeeName: string | null; notes: string | null; overrideDuplicateReference: boolean; createdAt: string }[];
  senderHistory: { id: number; createdAt: string; orderNumber: string; customerName: string; amount: number; transferMethod: string; transactionReference: string | null; status: string; reviewerName: string | null; rejectionReason: string | null }[];
};
type PaymentList = { items: Payment[]; total: number; page: number; limit: number };
type PaymentSetting = { id: number; method: "instapay" | "mobile_wallet"; displayNameAr: string; transferDestination: string; accountHolderName: string | null; instructionsAr: string | null; isActive: boolean; sortOrder: number };

const statusLabels: Record<string, string> = { pending_verification: "في انتظار المراجعة", confirmed: "مؤكد", rejected: "مرفوض", needs_review: "يحتاج مراجعة" };
const riskLabels = { none: "بدون تنبيه", yellow: "استخدم سابقًا", orange: "استخدام متكرر يحتاج مراجعة", red: "مراجعة دقيقة مطلوبة" };
const riskReasonLabels: Record<string, string> = { sender_reused: "الحساب مستخدم سابقًا", sender_frequent: "استخدام متكرر خلال 7 أيام", sender_previously_rejected: "مرتبط بتحويل مرفوض سابقًا", transaction_reference_duplicate: "رقم العملية مكرر", proof_duplicate: "صورة الإثبات مكررة" };

export default function AdminPayments() {
  const { admin } = useAuth();
  const { toast } = useToast();
  const [searchDraft, setSearchDraft] = useState("");
  const [q, setQ] = useState("");
  const [status, setStatus] = useState("pending_verification");
  const [plan, setPlan] = useState("all");
  const [method, setMethod] = useState("all");
  const [hasRisk, setHasRisk] = useState(false);
  const [selected, setSelected] = useState<PaymentDetail | null>(null);
  const [detailLoading, setDetailLoading] = useState(false);
  const [decisionNotes, setDecisionNotes] = useState("");
  const [rejectionReason, setRejectionReason] = useState("");
  const [overrideDuplicate, setOverrideDuplicate] = useState(false);
  const [saving, setSaving] = useState(false);
  const params = useMemo(() => { const value = new URLSearchParams({ status, plan, method }); if (q) value.set("q", q); if (hasRisk) value.set("hasRisk", "true"); return value.toString(); }, [status, plan, method, q, hasRisk]);
  const resource = useAdminResource<PaymentList>(`/api/admin/payments?${params}`);
  const can = (permission: string) => admin?.role === "owner" || admin?.role === "administrator" || admin?.permissions?.includes(permission);

  const openDetail = async (id: number) => { setDetailLoading(true); setDecisionNotes(""); setRejectionReason(""); setOverrideDuplicate(false); try { setSelected(await adminApi<PaymentDetail>(`/api/admin/payments/${id}`)); } catch (error) { toast({ title: "تعذر فتح التحويل", description: message(error), variant: "destructive" }); } finally { setDetailLoading(false); } };
  const review = async (decision: "confirmed" | "rejected" | "needs_review") => {
    if (!selected) return;
    if (decision === "rejected" && !rejectionReason.trim()) { toast({ title: "سبب الرفض مطلوب", variant: "destructive" }); return; }
    if (overrideDuplicate && !decisionNotes.trim()) { toast({ title: "اكتب سبب التجاوز الإداري", variant: "destructive" }); return; }
    if (decision === "confirmed" && !window.confirm(`تأكيد استلام ${selected.amount} جنيه للطلب ${selected.orderNumber}؟`)) return;
    setSaving(true);
    try {
      await adminApi(`/api/admin/payments/${selected.id}/review`, { method: "PATCH", body: JSON.stringify({ decision, notes: decisionNotes || null, rejectionReason: rejectionReason || null, overrideDuplicateReference: overrideDuplicate }) });
      toast({ title: decision === "confirmed" ? "تم تأكيد الدفع" : decision === "rejected" ? "تم رفض التحويل" : "تم تحويله إلى يحتاج مراجعة" });
      await resource.reload(); await openDetail(selected.id);
    } catch (error) { toast({ title: "تعذر حفظ قرار المراجعة", description: message(error), variant: "destructive" }); } finally { setSaving(false); }
  };

  return <section className="space-y-6" dir="rtl">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-black"><WalletCards className="h-7 w-7 text-secondary" />مراجعة المدفوعات</h1><p className="mt-1 text-sm text-muted-foreground">اعرف خلال ثوانٍ من دفع، والمبلغ، والحساب المحول منه، وأي تنبيه مخاطرة.</p></div><Button variant="outline" onClick={() => void resource.reload()}><RefreshCw className="ml-2 h-4 w-4" />تحديث</Button></div>
    <Card><CardContent className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-6"><div className="relative sm:col-span-2"><Search className="absolute right-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="pr-9" value={searchDraft} onChange={event => setSearchDraft(event.target.value)} onKeyDown={event => { if (event.key === "Enter") setQ(searchDraft.trim()); }} placeholder="طلب، عميل، هاتف، حساب، رقم عملية أو مبلغ" /><Button size="sm" className="absolute left-1.5 top-1.5 h-7" onClick={() => setQ(searchDraft.trim())}>بحث</Button></div><Filter value={status} onChange={setStatus} placeholder="الحالة" items={[["all", "كل الحالات"], ["pending_verification", "في انتظار المراجعة"], ["needs_review", "يحتاج مراجعة"], ["confirmed", "مؤكد"], ["rejected", "مرفوض"]]} /><Filter value={plan} onChange={setPlan} placeholder="نوع الدفع" items={[["all", "كل الأنواع"], ["deposit_100", "100 جنيه مقدم"], ["full", "دفع كامل"]]} /><Filter value={method} onChange={setMethod} placeholder="الوسيلة" items={[["all", "كل الوسائل"], ["instapay", "InstaPay"], ["mobile_wallet", "محفظة هاتف"]]} /><label className="flex items-center gap-2 rounded-md border px-3 text-sm"><Checkbox checked={hasRisk} onCheckedChange={checked => setHasRisk(checked === true)} />يوجد تنبيه</label></CardContent></Card>
    <AdminPageState loading={resource.loading} error={resource.error} empty={!resource.data?.items.length} onRetry={() => void resource.reload()}>
      <div className="grid gap-4 xl:grid-cols-2">{resource.data?.items.map(payment => <PaymentCard key={payment.id} payment={payment} onOpen={() => void openDetail(payment.id)} />)}</div>
    </AdminPageState>
    {resource.data && <p className="text-center text-xs text-muted-foreground">عدد النتائج: {resource.data.total}</p>}
    <PaymentSettingsPanel canEdit={Boolean(can("payments.settings"))} />

    <Dialog open={Boolean(selected || detailLoading)} onOpenChange={open => { if (!open) setSelected(null); }}><DialogContent className="max-h-[92dvh] max-w-5xl overflow-y-auto" dir="rtl"><DialogHeader className="text-right"><DialogTitle>مراجعة التحويل {selected?.orderNumber}</DialogTitle><DialogDescription>بيانات التحويل وسجل المرسل والقرار في شاشة واحدة.</DialogDescription></DialogHeader>{detailLoading && !selected ? <div className="py-12 text-center">جاري تحميل التفاصيل...</div> : selected && <div className="space-y-5">
      <RiskAlert payment={selected} />
      <div className="grid gap-4 md:grid-cols-3"><Info label="العميل" value={selected.customerName} sub={selected.customerPhone} /><Info label="المبلغ المحول" value={`${selected.amount.toLocaleString("ar-EG")} ج.م`} sub={`إجمالي الطلب ${selected.orderTotal.toLocaleString("ar-EG")} ج.م`} /><Info label="المدفوع / المتبقي" value={`${selected.paidAmount.toLocaleString("ar-EG")} / ${selected.remainingAmount.toLocaleString("ar-EG")} ج.م`} sub={selected.paymentPlan === "full" ? "دفع كامل" : "100 جنيه مقدم"} /><Info label="وسيلة التحويل" value={selected.transferMethod === "instapay" ? "InstaPay" : "محفظة هاتف"} /><Info label="المحول منه" value={selected.senderIdentifier} sub={`${selected.previousUseCount} استخدام سابق`} ltr /><Info label="رقم العملية" value={selected.transactionReference || "غير مرفق"} ltr /></div>
      {selected.proofImageUrl ? <Card><CardHeader><CardTitle className="text-base">صورة إثبات التحويل</CardTitle></CardHeader><CardContent><a href={selected.proofImageUrl} target="_blank" rel="noreferrer"><img src={selected.proofImageUrl} alt="إثبات التحويل" className="mx-auto max-h-96 rounded-xl border object-contain" /></a></CardContent></Card> : <div className="flex items-center gap-2 rounded-xl border border-dashed p-4 text-sm text-muted-foreground"><ImageIcon className="h-5 w-5" />لم يرفق العميل صورة، وهي اختيارية.</div>}
      {selected.senderHistory.length > 0 && <Card><CardHeader><CardTitle className="text-base">سجل التحويلات لهذا الرقم/الحساب</CardTitle></CardHeader><CardContent className="space-y-3">{selected.senderHistory.map(item => <div key={item.id} className={`grid gap-2 rounded-xl border p-3 text-sm sm:grid-cols-4 ${item.id === selected.id ? "bg-sky-50" : ""}`}><div><strong dir="ltr">{item.orderNumber}</strong><span className="block text-xs text-muted-foreground">{new Date(item.createdAt).toLocaleString("ar-EG")}</span></div><div>{item.customerName}<span className="block text-xs text-muted-foreground">{item.amount} ج.م</span></div><div>{statusLabels[item.status] || item.status}<span className="block text-xs text-muted-foreground">{item.transactionReference || "بدون رقم عملية"}</span></div><div>{item.reviewerName || "لم يراجع"}{item.rejectionReason && <span className="block text-xs text-red-700">{item.rejectionReason}</span>}</div></div>)}</CardContent></Card>}
      {selected.reviewHistory.length > 0 && <Card><CardHeader><CardTitle className="text-base">سجل قرارات المراجعة</CardTitle></CardHeader><CardContent className="space-y-2">{selected.reviewHistory.map(item => <div key={item.id} className="rounded-lg border p-3 text-sm"><strong>{item.employeeName || "موظف"}: {statusLabels[item.toStatus] || item.toStatus}</strong><span className="mr-2 text-xs text-muted-foreground">{new Date(item.createdAt).toLocaleString("ar-EG")}</span>{item.notes && <p>{item.notes}</p>}{item.overrideDuplicateReference && <Badge variant="destructive">Override مسجل</Badge>}</div>)}</CardContent></Card>}
      {["pending_verification", "needs_review"].includes(selected.status) && can("payments.review") && <Card className="border-2 border-slate-200"><CardHeader><CardTitle className="text-base">قرار الموظف</CardTitle></CardHeader><CardContent className="space-y-4"><div><Label htmlFor="review-notes">ملاحظات المراجعة</Label><Textarea id="review-notes" className="mt-2" value={decisionNotes} onChange={event => setDecisionNotes(event.target.value)} placeholder="ملاحظات داخلية أو سبب التجاوز الإداري" /></div>{can("payments.reject") && <div><Label htmlFor="reject-reason">سبب الرفض (إجباري عند الرفض)</Label><Input id="reject-reason" className="mt-2" value={rejectionReason} onChange={event => setRejectionReason(event.target.value)} placeholder="مثال: لم نعثر على التحويل" /></div>}{selected.riskReasons.includes("transaction_reference_duplicate") && can("payments.override") && <label className="flex items-start gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-sm"><Checkbox checked={overrideDuplicate} onCheckedChange={checked => setOverrideDuplicate(checked === true)} /><span><strong>Override إداري لرقم العملية المكرر</strong><br />يجب كتابة سبب واضح، وسيتم تسجيله في Audit Log.</span></label>}<div className="grid gap-2 sm:grid-cols-3">{can("payments.confirm") && <Button disabled={saving} className="bg-emerald-600 hover:bg-emerald-700" onClick={() => void review("confirmed")}><CheckCircle2 className="ml-2 h-4 w-4" />تأكيد الدفع</Button>}<Button disabled={saving} variant="outline" onClick={() => void review("needs_review")}><Clock3 className="ml-2 h-4 w-4" />يحتاج مراجعة</Button>{can("payments.reject") && <Button disabled={saving} variant="destructive" onClick={() => void review("rejected")}><XCircle className="ml-2 h-4 w-4" />رفض التحويل</Button>}</div></CardContent></Card>}
    </div>}</DialogContent></Dialog>
  </section>;
}

function PaymentCard({ payment, onOpen }: { payment: Payment; onOpen: () => void }) { return <Card className={`overflow-hidden border-r-4 ${payment.riskLevel === "red" ? "border-r-red-500" : payment.riskLevel === "orange" ? "border-r-orange-500" : payment.riskLevel === "yellow" ? "border-r-yellow-400" : "border-r-emerald-500"}`}><CardContent className="space-y-4 p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><div><strong dir="ltr" className="text-lg">{payment.orderNumber}</strong><p className="text-sm font-bold">{payment.customerName}</p><span dir="ltr" className="block text-right text-xs text-muted-foreground">{payment.customerPhone}</span></div><div className="text-left"><Badge className={statusClass(payment.status)}>{statusLabels[payment.status]}</Badge><span className="mt-1 block text-xs text-muted-foreground">{new Date(payment.createdAt).toLocaleString("ar-EG")}</span></div></div><div className="grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-3 text-sm sm:grid-cols-4"><Mini label="المبلغ" value={`${payment.amount} ج.م`} /><Mini label="نوع الدفع" value={payment.paymentPlan === "full" ? "كامل" : "100 مقدم"} /><Mini label="الوسيلة" value={payment.transferMethod === "instapay" ? "InstaPay" : "محفظة"} /><Mini label="المتبقي" value={`${payment.remainingAmount} ج.م`} /></div><div className="flex items-center justify-between gap-3"><div className="min-w-0"><span className="text-xs text-muted-foreground">المحول منه</span><strong dir="ltr" className="block truncate text-right">{payment.senderIdentifier}</strong>{payment.previousUseCount > 0 && <span className="text-xs text-amber-700">استخدم {payment.previousUseCount} مرة سابقًا</span>}</div><RiskBadge level={payment.riskLevel} /></div><div className="flex items-center justify-between"><span className="flex items-center gap-1 text-xs text-muted-foreground">{payment.proofImageUrl ? <><ImageIcon className="h-4 w-4" />صورة مرفقة</> : "بدون صورة"}</span><Button size="sm" onClick={onOpen}><Eye className="ml-1 h-4 w-4" />مراجعة الآن</Button></div></CardContent></Card>; }
function RiskAlert({ payment }: { payment: PaymentDetail }) { if (payment.riskLevel === "none") return <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-900"><strong>لا توجد إشارات تكرار ظاهرة</strong></div>; const style = payment.riskLevel === "red" ? "border-red-300 bg-red-50 text-red-950" : payment.riskLevel === "orange" ? "border-orange-300 bg-orange-50 text-orange-950" : "border-yellow-300 bg-yellow-50 text-yellow-950"; const previous = payment.senderHistory.find(item => item.id !== payment.id); return <div className={`rounded-xl border p-4 ${style}`}><div className="flex items-start gap-3"><ShieldAlert className="h-6 w-6 shrink-0" /><div><strong className="block text-lg">⚠️ {riskLabels[payment.riskLevel]}</strong><p className="text-sm">هذا تنبيه للمراجعة ولا يرفض التحويل تلقائيًا.</p><ul className="mt-2 list-inside list-disc text-sm">{payment.riskReasons.map(reason => <li key={reason}>{riskReasonLabels[reason] || reason}</li>)}</ul>{previous && <div className="mt-3 rounded-lg bg-white/70 p-3 text-xs"><strong>آخر استخدام سابق:</strong> <span dir="ltr">{previous.orderNumber}</span> — {statusLabels[previous.status] || previous.status}<br />{new Date(previous.createdAt).toLocaleString("ar-EG")}</div>}<p className="mt-2 text-xs">إجمالي الاستخدامات السابقة: {payment.previousUseCount}</p></div></div></div>; }
function RiskBadge({ level }: { level: Payment["riskLevel"] }) { const color = level === "red" ? "bg-red-100 text-red-800" : level === "orange" ? "bg-orange-100 text-orange-800" : level === "yellow" ? "bg-yellow-100 text-yellow-800" : "bg-emerald-100 text-emerald-800"; return <Badge className={color}>{level === "none" ? "آمن ظاهريًا" : riskLabels[level]}</Badge>; }
function PaymentSettingsPanel({ canEdit }: { canEdit: boolean }) { const resource = useAdminResource<PaymentSetting[]>("/api/admin/payments/settings"); return <Card><CardHeader><CardTitle className="flex items-center gap-2"><Settings2 className="h-5 w-5" />بيانات التحويل التي تظهر للعميل</CardTitle></CardHeader><CardContent><AdminPageState loading={resource.loading} error={resource.error} empty={!resource.data?.length} onRetry={() => void resource.reload()}><div className="grid gap-4 lg:grid-cols-2">{resource.data?.map(setting => <PaymentSettingCard key={setting.id} setting={setting} canEdit={canEdit} onSaved={() => resource.reload()} />)}</div></AdminPageState></CardContent></Card>; }
function PaymentSettingCard({ setting, canEdit, onSaved }: { setting: PaymentSetting; canEdit: boolean; onSaved: () => Promise<void> }) { const { toast } = useToast(); const [draft, setDraft] = useState(setting); const [saving, setSaving] = useState(false); useEffect(() => setDraft(setting), [setting]); const save = async () => { setSaving(true); try { await adminApi(`/api/admin/payments/settings/${setting.method}`, { method: "PUT", body: JSON.stringify(draft) }); toast({ title: "تم تحديث بيانات التحويل" }); await onSaved(); } catch (error) { toast({ title: "تعذر الحفظ", description: message(error), variant: "destructive" }); } finally { setSaving(false); } }; return <div className="space-y-3 rounded-2xl border p-4"><div className="flex items-center justify-between"><strong>{setting.displayNameAr}</strong><Badge variant={draft.isActive ? "outline" : "secondary"}>{draft.isActive ? "مفعلة" : "متوقفة"}</Badge></div><div><Label>الاسم الظاهر</Label><Input disabled={!canEdit} value={draft.displayNameAr} onChange={event => setDraft(value => ({ ...value, displayNameAr: event.target.value }))} /></div><div><Label>رقم/حساب الاستقبال</Label><Input disabled={!canEdit} dir="ltr" value={draft.transferDestination} onChange={event => setDraft(value => ({ ...value, transferDestination: event.target.value }))} /></div><div><Label>اسم صاحب الحساب</Label><Input disabled={!canEdit} value={draft.accountHolderName || ""} onChange={event => setDraft(value => ({ ...value, accountHolderName: event.target.value || null }))} /></div><div><Label>تعليمات العميل</Label><Textarea disabled={!canEdit} value={draft.instructionsAr || ""} onChange={event => setDraft(value => ({ ...value, instructionsAr: event.target.value || null }))} /></div>{canEdit && <div className="flex items-center justify-between"><label className="flex items-center gap-2 text-sm"><Checkbox checked={draft.isActive} onCheckedChange={checked => setDraft(value => ({ ...value, isActive: checked === true }))} />متاحة للعملاء</label><Button size="sm" disabled={saving} onClick={() => void save()}>{saving ? "جاري الحفظ..." : "حفظ"}</Button></div>}</div>; }
function Filter({ value, onChange, placeholder, items }: { value: string; onChange: (value: string) => void; placeholder: string; items: [string, string][] }) { return <Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue placeholder={placeholder} /></SelectTrigger><SelectContent>{items.map(([itemValue, label]) => <SelectItem key={itemValue} value={itemValue}>{label}</SelectItem>)}</SelectContent></Select>; }
function Info({ label, value, sub, ltr = false }: { label: string; value: string; sub?: string; ltr?: boolean }) { return <div className="rounded-xl border bg-slate-50 p-3"><span className="text-xs text-muted-foreground">{label}</span><strong className="block break-all" dir={ltr ? "ltr" : undefined}>{value}</strong>{sub && <small className="text-muted-foreground">{sub}</small>}</div>; }
function Mini({ label, value }: { label: string; value: string }) { return <div><span className="block text-xs text-muted-foreground">{label}</span><strong>{value}</strong></div>; }
function statusClass(status: Payment["status"]) { return status === "confirmed" ? "bg-emerald-100 text-emerald-800" : status === "rejected" ? "bg-red-100 text-red-800" : status === "needs_review" ? "bg-orange-100 text-orange-800" : "bg-amber-100 text-amber-800"; }
function message(error: unknown) { return error instanceof Error ? error.message : String(error); }
