import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { config } from "../lib/config";

type Inbox = {
  id: number;
  name: string;
  inbox_identifier?: string;
  identifier?: string;
  hmac_token?: string;
  channel_type?: string;
};

const INBOX_NAME = "Website Chat – Maktaba Dot Com";

async function chatwootAccountRequest<T>(path: string, init?: RequestInit): Promise<T> {
  if (!config.CHATWOOT_BASE_URL || !config.CHATWOOT_ACCOUNT_ACCESS_TOKEN) throw new Error("CHATWOOT_BASE_URL and CHATWOOT_ACCOUNT_ACCESS_TOKEN are required");
  const response = await fetch(`${config.CHATWOOT_BASE_URL.replace(/\/$/, "")}${path}`, {
    ...init,
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json",
      api_access_token: config.CHATWOOT_ACCOUNT_ACCESS_TOKEN,
      ...init?.headers,
    },
    signal: AbortSignal.timeout(config.CHATWOOT_REQUEST_TIMEOUT_MS),
  });
  if (!response.ok) throw new Error(`Chatwoot provisioning request failed (${response.status})`);
  return response.json() as Promise<T>;
}

async function main() {
  if (!config.CHATWOOT_ACCOUNT_ID) throw new Error("CHATWOOT_ACCOUNT_ID is required");
  const path = `/api/v1/accounts/${config.CHATWOOT_ACCOUNT_ID}/inboxes`;
  const existingResponse = await chatwootAccountRequest<Inbox[] | { payload?: Inbox[] }>(path);
  const inboxes = Array.isArray(existingResponse) ? existingResponse : existingResponse.payload ?? [];
  let inbox = inboxes.find(item => item.name === INBOX_NAME);
  if (inbox?.channel_type && inbox.channel_type !== "Channel::Api") throw new Error(`An inbox named ${INBOX_NAME} exists but it is not an API inbox`);
  if (!inbox) {
    inbox = await chatwootAccountRequest<Inbox>(path, {
      method: "POST",
      body: JSON.stringify({ name: INBOX_NAME, channel: { type: "api" } }),
    });
  }
  // Chatwoot 4.15 exposes an API channel identifier as `inbox_identifier`.
  // Retain the legacy fallback so the one-time provisioning command remains
  // compatible with older installations without weakening secret handling.
  const identifier = inbox.inbox_identifier ?? inbox.identifier ?? config.CHATWOOT_API_INBOX_IDENTIFIER;
  const hmacToken = inbox.hmac_token ?? config.CHATWOOT_HMAC_TOKEN;
  if (!identifier) throw new Error("Chatwoot did not return the inbox identifier");
  if (!hmacToken) throw new Error("Chatwoot did not return the HMAC token; copy it from the inbox settings and run again");

  const baseUrl = config.CHATWOOT_BASE_URL!;
  const realtimeUrl = new URL(baseUrl);
  realtimeUrl.protocol = realtimeUrl.protocol === "https:" ? "wss:" : "ws:";
  realtimeUrl.pathname = "/cable";
  realtimeUrl.search = "";
  const output = [
    "# Generated by provision-chatwoot-inbox. Keep this file private.",
    "# Provisioning never publishes the widget. Enable it only after real E2E tests pass.",
    "WEBSITE_CHAT_ENABLED=false",
    `CHATWOOT_BASE_URL=${baseUrl}`,
    `CHATWOOT_REALTIME_URL=${realtimeUrl.toString()}`,
    `CHATWOOT_API_INBOX_ID=${inbox.id}`,
    `CHATWOOT_API_INBOX_IDENTIFIER=${identifier}`,
    `CHATWOOT_HMAC_TOKEN=${hmacToken}`,
    "",
  ].join("\n");
  const outputPath = resolve(process.env.CHATWOOT_PROVISION_OUTPUT ?? ".chatwoot-inbox.env");
  await writeFile(outputPath, output, { mode: 0o600 });
  process.stdout.write(`Chatwoot API inbox is ready (id=${inbox.id}, name=${inbox.name}). Private runtime settings were written to ${outputPath}.\n`);
}

main().catch(error => {
  process.stderr.write(`${error instanceof Error ? error.message : "Chatwoot provisioning failed"}\n`);
  process.exitCode = 1;
});
