docRoot                   /home/store.maktabaa.com/public_html
vhDomain                  store.maktabaa.com
enableGzip                1

errorlog $VH_ROOT/logs/error.log {
  useServer               0
  logLevel                WARN
  rollingSize             10M
}

accesslog $VH_ROOT/logs/access.log {
  useServer               0
  rollingSize             10M
  keepDays                10
}

extprocessor store_gateway {
  type                    proxy
  address                 127.0.0.1:19080
  maxConns                2000
  initTimeout             30
  retryTimeout            30
  pcKeepAliveTimeout      600
  respBuffer              1
}

context /.well-known/acme-challenge {
  location                /usr/local/lsws/Example/html/.well-known/acme-challenge
  allowBrowse             1
}

context / {
  type                    proxy
  handler                 store_gateway
}

rewrite {
  enable                  1
  rules                   <<<END_rules
RewriteCond %{HTTPS} !=on
RewriteCond %{REQUEST_URI} !^/\.well-known/acme-challenge/
RewriteRule ^ https://store.maktabaa.com%{REQUEST_URI} [R=301,L]
END_rules
}

