import { Link } from "wouter";
import { BookOpen, Facebook, FileText, GraduationCap, HelpCircle, Instagram, LibraryBig, Mail, MapPin, MessageCircle, PackageSearch, Phone, RotateCcw, Shield, Sparkles, Truck } from "lucide-react";
import { FaWhatsapp, FaTiktok, FaTelegram } from "react-icons/fa";
import { getGetSiteSettingsQueryKey, useGetSiteSettings } from "@workspace/api-client-react";
import { useQuery } from "@tanstack/react-query";
import { DEFAULT_BRAND_LOGO } from "@/lib/brand";

type HelpItem = { id: number; textAr: string; url: string; target: "same_tab" | "new_tab"; icon?: string | null; deviceVisibility: "all" | "desktop" | "mobile" };
type HelpContent = { id: number | null; titleAr: string; isActive: boolean; items: HelpItem[] };
const icons = { "help-circle": HelpCircle, "package-search": PackageSearch, truck: Truck, "rotate-ccw": RotateCcw, shield: Shield, "file-text": FileText, "message-circle": MessageCircle, phone: Phone, mail: Mail, "book-open": BookOpen } as const;

export function Footer() {
  const { data: settings } = useGetSiteSettings({ query: { queryKey: getGetSiteSettingsQueryKey(), staleTime: 60_000, refetchOnWindowFocus: true } });
  const { data: help } = useQuery({ queryKey: ["public-help-content"], queryFn: async () => { const response = await fetch("/api/content/help"); if (!response.ok) throw new Error("تعذر تحميل روابط المساعدة"); return response.json() as Promise<HelpContent>; }, staleTime: 60_000, refetchOnWindowFocus: true });
  const whatsapp = settings?.whatsappNumber?.replace(/\D/g, "");
  const socialLinks = [
    settings?.facebookUrl && [settings.facebookUrl, Facebook, "فيسبوك"], settings?.instagramUrl && [settings.instagramUrl, Instagram, "إنستجرام"], settings?.tiktokUrl && [settings.tiktokUrl, FaTiktok, "تيك توك"], settings?.telegramUrl && [settings.telegramUrl, FaTelegram, "تليجرام"], whatsapp && [`https://wa.me/${whatsapp}`, FaWhatsapp, "واتساب"],
  ].filter(Boolean) as [string, typeof Facebook, string][];
  const footerLogo = settings?.darkBackgroundLogoUrl || settings?.mainLogoUrl || settings?.logoUrl || DEFAULT_BRAND_LOGO;
  return <footer className="footer-motion-scene relative overflow-hidden border-t-4 border-sky-500 bg-slate-950 pb-24 pt-14 text-white md:pb-8">
    <div className="footer-motion-glow" aria-hidden="true" />
    <div className="footer-motion-stars" aria-hidden="true">{Array.from({ length: 10 }, (_, index) => <i key={index} />)}</div>
    <div className="footer-motion-icons" aria-hidden="true"><BookOpen /><GraduationCap /><LibraryBig /><Sparkles /></div>
    <div className="container relative z-10 mx-auto grid grid-cols-1 gap-10 px-4 sm:grid-cols-2 lg:grid-cols-4">
      <div className="footer-motion-column"><Link href="/" className="inline-flex min-h-12 items-center" aria-label="الصفحة الرئيسية">{footerLogo ? <img src={footerLogo} alt={settings?.storeNameAr || "مكتبة دوت كوم"} width="180" height="60" className="footer-motion-logo max-h-14 max-w-48 object-contain object-right" /> : <span className="text-3xl font-black">{settings?.storeNameAr || "مكتبة دوت كوم"}</span>}</Link><p className="mt-5 max-w-sm leading-7 text-slate-400">متجر عربي للكتب التعليمية والمراجعات، ببيانات أسعار ومخزون محدثة مباشرة من إدارة المكتبة.</p><div className="mt-6 flex flex-wrap gap-3">{socialLinks.map(([href, Icon, label]) => <a key={label} href={href} target="_blank" rel="noreferrer" aria-label={label} title={label} className="footer-social-link rounded-xl bg-white/10 p-2.5 text-slate-300 transition hover:bg-sky-500 hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-300"><Icon className="h-5 w-5" /></a>)}</div></div>
      <div className="footer-motion-column"><h2 className="mb-5 text-lg font-black">اكتشف المكتبة</h2><ul className="footer-motion-links space-y-3 text-slate-400"><li><Link href="/catalog" className="hover:text-white">كل الكتب</Link></li><li><Link href="/offers" className="hover:text-white">العروض</Link></li><li><Link href="/stages" className="hover:text-white">المراحل والصفوف</Link></li><li><Link href="/publishers" className="hover:text-white">دور النشر</Link></li><li><Link href="/categories" className="hover:text-white">التصنيفات</Link></li></ul></div>
      {help?.isActive && <div className="footer-motion-column"><h2 className="mb-5 text-lg font-black">{help.titleAr}</h2><ul className="footer-motion-links space-y-3 text-slate-400">{help.items.map(item => { const Icon = icons[(item.icon || "help-circle") as keyof typeof icons] || HelpCircle; const visibility = item.deviceVisibility === "desktop" ? "hidden md:list-item" : item.deviceVisibility === "mobile" ? "list-item md:hidden" : ""; const content = <span className="inline-flex items-center gap-2"><Icon className="h-4 w-4" />{item.textAr}</span>; return <li key={item.id} className={visibility}>{item.url.startsWith("/") && item.target === "same_tab" ? <Link href={item.url} className="hover:text-white">{content}</Link> : <a href={item.url} target={item.target === "new_tab" ? "_blank" : undefined} rel={item.target === "new_tab" ? "noreferrer" : undefined} className="hover:text-white">{content}</a>}</li>; })}</ul></div>}
      <div className="footer-motion-column"><h2 className="mb-5 text-lg font-black">تواصل معنا</h2><ul className="space-y-4 text-slate-400">{settings?.address && <li className="flex gap-3"><MapPin className="mt-1 h-5 w-5 shrink-0 text-sky-400" /><span>{settings.address}</span></li>}{settings?.phoneNumber && <li className="flex gap-3"><Phone className="h-5 w-5 shrink-0 text-sky-400" /><a dir="ltr" href={`tel:${settings.phoneNumber}`}>{settings.phoneNumber}</a></li>}{settings?.email && <li className="flex gap-3"><Mail className="h-5 w-5 shrink-0 text-sky-400" /><a dir="ltr" href={`mailto:${settings.email}`}>{settings.email}</a></li>}</ul><p className="footer-payment-note mt-5 rounded-xl border border-amber-300/20 bg-amber-300/10 p-3 text-sm text-amber-100">تأكيد الطلب بتحويل 100 جنيه أو دفع القيمة كاملة، مع مراجعة بشرية لكل تحويل.</p></div>
    </div>
    <div className="container relative z-10 mx-auto mt-12 border-t border-white/10 px-4 pt-7 text-center text-sm text-slate-500">جميع الحقوق محفوظة © {new Date().getFullYear()} {settings?.storeNameAr || "مكتبة دوت كوم"}</div>
    {whatsapp && <a href={`https://wa.me/${whatsapp}`} target="_blank" rel="noreferrer" aria-label="استفسار عبر واتساب" title="استفسار عبر واتساب" className="fixed bottom-20 left-5 z-40 rounded-full bg-[#25D366] p-3.5 text-white shadow-xl transition hover:scale-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-300 md:bottom-6"><FaWhatsapp className="h-7 w-7" /></a>}
  </footer>;
}
